In [1]:
import numpy as np

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# Get specific element [r, c]
a[1, 5]

np.int64(13)

In [14]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:, 0]

array([1, 8])

In [24]:
# Getting a little fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [28]:
# Change value
a[1, 2] = 7
print(a)

a[:, 1] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9  7 11 12 13 14]]
[[ 1  5  3  4  5  6  7]
 [ 8  5  7 11 12 13 14]]


* 3d example

In [45]:
b = np.array([ [[1,2],[3,4]], [[5,6],[7,8]] ])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
# Get specific element
b[0,1,1]

np.int64(4)

In [47]:
#replace
b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
