In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3], dtype="int16")
print(a)

[1 2 3]


In [4]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
# Get Dimension
b.ndim

2

In [8]:
# Get Shape
b.shape

(2, 3)

In [12]:
# Get Type
a.dtype

dtype('int16')

In [15]:
# Get Size
a.itemsize

2

In [17]:
# Get Total Size
a.nbytes

6