In [2]:
import numpy as np

In [22]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# All 1s matrix
np.ones((4,2,3), dtype="int32")

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [24]:
# Any other number 
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [29]:
# Random decimal number 
np.random.rand(4,2)

array([[0.06210574, 0.70950018],
       [0.04407104, 0.44272393],
       [0.67612352, 0.74660639],
       [0.60981289, 0.21471604]])

In [33]:
# Random integer number 
np.random.randint(7, size=(3,3))

array([[5, 0, 6],
       [6, 0, 1],
       [2, 4, 5]])

In [34]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
arr = np.array([[1,2,3]])
repeat_arr = np.repeat(arr,3, axis=0)
print(repeat_arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [52]:
# Small practice 
output = np.ones((5,5), dtype="int32")

zeros = np.zeros((3,3), dtype="int32")
zeros[1,1] = 7

output[1:4, 1:4] = zeros
print(output)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 7 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [53]:
# Be careful on copying
a = np.array([1,2,3])
b = a.copy()
b[0] = 7

print(a)
print(b)

[1 2 3]
[7 2 3]
