In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [8]:
a ** 2

array([ 1,  4,  9, 16])

In [9]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [20]:
x = np.ones((2,3))
print(a)

y = np.full((3,2), 2)
print(b)

np.matmul(x,y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [22]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

 ### Statistics


In [23]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.min(stats)

np.int64(1)

In [31]:
np.max(stats, axis=1)

array([3, 6])